[tools] # list the tools you want to install under this header
stylua = { source = "JohnnyMorganz/StyLua", version = "0.11.3" }
wally = { source = "UpliftGames/wally", version = "0.3.1"}
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
wally-package-types = {source = "JohnnyMorganz/wally-package-types", version = "1.2.0"}
tarmac = {source = "Roblox/tarmac", version = "0.7.0"}